### ISSUE TITLE
Get Internal Server Error when trying to get last event form API

### ISSUE THREAD

**Issue by aryanjaya** [baliphp/phpbali-site#107]
**Condition**:
When I try to get last event using api/event/last, i get "Internal Server Error" with message "Trying to get property 'id' of non-object". This happen because I don't have any event in my database.

**Reproduce**:
- Just try "Instalasi" section.
- Try get last event via "api/event/last" using web browser

**Idea for a solution**:
- You can read this issue laravel/framework/issues/22892 for reference

**Comment by satyakresna** [comment]
Looks good to me. Please execute.

**Comment by RobinTHOREL** [comment]
I'll look forward this issue

**Comment by satyakresna** [comment]
Hi @RobinTHOREL, I already check the pull request by @aryanjaya and merged into our repository. Thank you @aryanjaya. 🙏
