### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by RobinTHOREL** [baliphp/phpbali-site#109]
They miss some informations to setup the project in your readme.

Like the rights to `storage/` folder are wrongs.

We need to generate the app key by running `└> docker-compose exec app php artisan key:generate`

**Comment by satyakresna** [comment]
Hi @RobinTHOREL, thanks for letting us know about the missing step in the installation using docker. Indeed, it should be run `docker-compose exec app php artisan key:generate` before running `artisan migrate` command. I will update the readme documentation.

About the `storage/` you mention above, is that about change the permission in `storage/` in Dockerfile?

Anyway, @wayanjimmy has created a docker configuration so I will let him know about this issue.

**Comment by satyakresna** [comment]
I will close this issue since no longer activity. Please feel free to comment if you need assitance related this issue. Thanks.
