### ISSUE TITLE
Pertimbangan mencabut gambar poster acara di halaman utama

### ISSUE THREAD

**Issue by satyakresna** [BaliPHP/phpbali-site#25]
Berdasarkan riset ke beberapa web, setiap kali ada event, di halaman utama tidak dimunculkan gambar poster acara mereka. Sebenarnya menurut pandangan pribadi, user cuma butuh informasi apa aja yang ada di event kita (meliputi nama acara, tanggal, tempat dan waktu.

Sampai bulan kemarin, PHPBali membuat poster dan poster tersebut diupload ke website phpbali.com dan ketika di taruh di halaman utama tidak terlihat elok karena warna background poster dan font wording event.

Untuk ke depannya kita akan menghapus opsi menaruh gambar poster acara di halaman utama dan akan kita taruh di halaman terpisah.

Daftar web yang diriset:
balijs.com
gdgbali.com
bandung.js.org
phpindonesia.id
jakarta.js.org

**Comment by balinux** [comment]
kenapa tidak menggunakan slider?

**Comment by satyakresna** [comment]
Slider tidak efektif dan pengguna ketika masuk ke landing page ingin melihat kegiatan terkini. Aku udah menulis untuk rancangan website PHPBali yang baru di sini: https://www.notion.so/satyakresna/Analisa-Web-PHPBali-848ffaff13c24dec813d9fee6c4ba430
