### ISSUE TITLE
Integrasi dengan CI/CD Gitlab

### ISSUE THREAD

**Issue by satyakresna** [BaliPHP/phpbali-site#26]
Berdasarkan percakapan dengan kak @wayanjimmy , kita akan menggunakan CI/CD Gitlab karena banyak developer yang familiar dan tutorialnya yang cukup banyak serta ada CI/CD Gitlab yang support Laravel, artikel nya [di sini](http://lorisleiva.com/laravel-deployment-using-gitlab-pipelines/). Hanya saja opsi ini sampai berlaku di tahun depan (22 Maret 2019), setelah itu akan berbayar.

Sementara ini belum aku coba dan semoga berhasil.

**Comment by wayanjimmy** [comment]
sebagai pilihan cadangan karena jika sudah di VPS sesuai #14 maka bisa juga menggunakan github web hook 

**Referensi**
- [https://serversforhackers.com/c/automating-deployment-from-github](https://serversforhackers.com/c/automating-deployment-from-github)

**Comment by satyakresna** [comment]
[SOLVED], sudah berhasil dengan bantuan tutorial servers for hacker dan kak Wayan Jimmy menggunakan Github Webhook.
